sudo: required

services:
  - docker
  - postgresql

language: python
python:
  - "3.6"

jobs:
  include:
    - stage: Start local development environment
      before_script:
        - docker-compose up --build -d
      script:
        - docker-compose run web python manage.py help
      after_script:
        - docker-compose down
    - stage: Start production ready server
      before_script:
      - psql -c "CREATE DATABASE db_app;" -U postgres
      - psql -c "CREATE USER db_user WITH PASSWORD 'db_pass';" -U postgres
      script:
        - docker build . --file docker/dokku/Dockerfile
